-- MySQL Script generated by MySQL Workbench
-- Sat May 13 11:44:45 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema smhackbot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema smhackbot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smhackbot` DEFAULT CHARACTER SET utf8 ;
USE `smhackbot` ;

-- -----------------------------------------------------
-- Table `smhackbot`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smhackbot`.`groups` (
  `group_id` INT NOT NULL,
  PRIMARY KEY (`group_id`),
  UNIQUE INDEX `group_id_UNIQUE` (`group_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smhackbot`.`nfc_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smhackbot`.`nfc_card` (
  `nfc_id` INT NOT NULL AUTO_INCREMENT,
  `loc_x` VARCHAR(45) NULL,
  `loc_y` VARCHAR(45) NULL,
  `Group_group_id` INT NOT NULL,
  PRIMARY KEY (`nfc_id`, `Group_group_id`),
  INDEX `fk_nfc_card_Group_idx` (`Group_group_id` ASC),
  CONSTRAINT `fk_nfc_card_Group`
    FOREIGN KEY (`Group_group_id`)
    REFERENCES `smhackbot`.`groups` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smhackbot`.`activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smhackbot`.`activity` (
  `activity_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `env_impact` INT NOT NULL,
  `nfc_card_nfc_id` INT NOT NULL,
  PRIMARY KEY (`activity_id`),
  INDEX `fk_activity_nfc_card1_idx` (`nfc_card_nfc_id` ASC),
  CONSTRAINT `fk_activity_nfc_card1`
    FOREIGN KEY (`nfc_card_nfc_id`)
    REFERENCES `smhackbot`.`nfc_card` (`nfc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smhackbot`.`activity_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smhackbot`.`activity_history` (
  `timestamp` DATETIME NOT NULL,
  `nfc_card_nfc_id` INT NOT NULL,
  PRIMARY KEY (`timestamp`, `nfc_card_nfc_id`),
  INDEX `fk_activity_history_nfc_card1_idx` (`nfc_card_nfc_id` ASC),
  CONSTRAINT `fk_activity_history_nfc_card1`
    FOREIGN KEY (`nfc_card_nfc_id`)
    REFERENCES `smhackbot`.`nfc_card` (`nfc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
